package cpw.mods.fml.common;

import java.util.ArrayList;
import java.util.List;

/**
 * Stub for cpw.mods.fml.common.ModMetadata (Forge 1.6.4).
 * Holds the descriptive metadata loaded from {@code mcmod.info} or
 * the {@code @Mod} annotation. All fields are public to mirror the
 * upstream API since some 1.6 mods set them directly.
 */
public class ModMetadata {
    public String modId = "";
    public String name = "";
    public String description = "";
    public String url = "";
    public String logoFile = "";
    public String version = "";
    public String[] screenshots = new String[0];
    public String credits = "";
    public List<String> authorList = new ArrayList<>();
    public String parent = "";
    public List<String> screenshotsList = new ArrayList<>();
    public boolean autogenerated = false;
    public boolean useDependencyInformation = false;
    public List<ArtifactVersion> requiredMods = new ArrayList<>();
    public List<ArtifactVersion> dependencies = new ArrayList<>();
    public List<ArtifactVersion> dependants = new ArrayList<>();

    public ModMetadata() {}

    public ModMetadata(String id) {
        this.modId = id;
        this.name = id;
    }

    public String getName() { return name; }
    public String getModId() { return modId; }
    public String getVersion() { return version; }
    public String getDescription() { return description; }
    public String getUrl() { return url; }
}
